/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	varmorv1beta1 "github.com/bytedance/vArmor/apis/varmor/v1beta1"
	versioned "github.com/bytedance/vArmor/pkg/client/clientset/versioned"
	internalinterfaces "github.com/bytedance/vArmor/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/bytedance/vArmor/pkg/client/listers/varmor/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VarmorPolicyInformer provides access to a shared informer and lister for
// VarmorPolicies.
type VarmorPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.VarmorPolicyLister
}

type varmorPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewVarmorPolicyInformer constructs a new informer for VarmorPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVarmorPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVarmorPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredVarmorPolicyInformer constructs a new informer for VarmorPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVarmorPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1beta1().VarmorPolicies(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1beta1().VarmorPolicies(namespace).Watch(context.TODO(), options)
			},
		},
		&varmorv1beta1.VarmorPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *varmorPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVarmorPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *varmorPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&varmorv1beta1.VarmorPolicy{}, f.defaultInformer)
}

func (f *varmorPolicyInformer) Lister() v1beta1.VarmorPolicyLister {
	return v1beta1.NewVarmorPolicyLister(f.Informer().GetIndexer())
}
