apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: varmor-manager
  namespace: varmor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: varmor-manager
subjects:
- kind: ServiceAccount
  name: varmor-manager
  namespace: varmor
