/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/bytedance/vArmor/apis/varmor/v1beta1"
	scheme "github.com/bytedance/vArmor/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VarmorClusterPoliciesGetter has a method to return a VarmorClusterPolicyInterface.
// A group's client should implement this interface.
type VarmorClusterPoliciesGetter interface {
	VarmorClusterPolicies() VarmorClusterPolicyInterface
}

// VarmorClusterPolicyInterface has methods to work with VarmorClusterPolicy resources.
type VarmorClusterPolicyInterface interface {
	Create(ctx context.Context, varmorClusterPolicy *v1beta1.VarmorClusterPolicy, opts v1.CreateOptions) (*v1beta1.VarmorClusterPolicy, error)
	Update(ctx context.Context, varmorClusterPolicy *v1beta1.VarmorClusterPolicy, opts v1.UpdateOptions) (*v1beta1.VarmorClusterPolicy, error)
	UpdateStatus(ctx context.Context, varmorClusterPolicy *v1beta1.VarmorClusterPolicy, opts v1.UpdateOptions) (*v1beta1.VarmorClusterPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.VarmorClusterPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.VarmorClusterPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.VarmorClusterPolicy, err error)
	VarmorClusterPolicyExpansion
}

// varmorClusterPolicies implements VarmorClusterPolicyInterface
type varmorClusterPolicies struct {
	client rest.Interface
}

// newVarmorClusterPolicies returns a VarmorClusterPolicies
func newVarmorClusterPolicies(c *CrdV1beta1Client) *varmorClusterPolicies {
	return &varmorClusterPolicies{
		client: c.RESTClient(),
	}
}

// Get takes name of the varmorClusterPolicy, and returns the corresponding varmorClusterPolicy object, and an error if there is any.
func (c *varmorClusterPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.VarmorClusterPolicy, err error) {
	result = &v1beta1.VarmorClusterPolicy{}
	err = c.client.Get().
		Resource("varmorclusterpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VarmorClusterPolicies that match those selectors.
func (c *varmorClusterPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.VarmorClusterPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.VarmorClusterPolicyList{}
	err = c.client.Get().
		Resource("varmorclusterpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested varmorClusterPolicies.
func (c *varmorClusterPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("varmorclusterpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a varmorClusterPolicy and creates it.  Returns the server's representation of the varmorClusterPolicy, and an error, if there is any.
func (c *varmorClusterPolicies) Create(ctx context.Context, varmorClusterPolicy *v1beta1.VarmorClusterPolicy, opts v1.CreateOptions) (result *v1beta1.VarmorClusterPolicy, err error) {
	result = &v1beta1.VarmorClusterPolicy{}
	err = c.client.Post().
		Resource("varmorclusterpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(varmorClusterPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a varmorClusterPolicy and updates it. Returns the server's representation of the varmorClusterPolicy, and an error, if there is any.
func (c *varmorClusterPolicies) Update(ctx context.Context, varmorClusterPolicy *v1beta1.VarmorClusterPolicy, opts v1.UpdateOptions) (result *v1beta1.VarmorClusterPolicy, err error) {
	result = &v1beta1.VarmorClusterPolicy{}
	err = c.client.Put().
		Resource("varmorclusterpolicies").
		Name(varmorClusterPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(varmorClusterPolicy).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *varmorClusterPolicies) UpdateStatus(ctx context.Context, varmorClusterPolicy *v1beta1.VarmorClusterPolicy, opts v1.UpdateOptions) (result *v1beta1.VarmorClusterPolicy, err error) {
	result = &v1beta1.VarmorClusterPolicy{}
	err = c.client.Put().
		Resource("varmorclusterpolicies").
		Name(varmorClusterPolicy.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(varmorClusterPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the varmorClusterPolicy and deletes it. Returns an error if one occurs.
func (c *varmorClusterPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("varmorclusterpolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *varmorClusterPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("varmorclusterpolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched varmorClusterPolicy.
func (c *varmorClusterPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.VarmorClusterPolicy, err error) {
	result = &v1beta1.VarmorClusterPolicy{}
	err = c.client.Patch(pt).
		Resource("varmorclusterpolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
