/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	varmorv1beta1 "github.com/bytedance/vArmor/apis/varmor/v1beta1"
	versioned "github.com/bytedance/vArmor/pkg/client/clientset/versioned"
	internalinterfaces "github.com/bytedance/vArmor/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "github.com/bytedance/vArmor/pkg/client/listers/varmor/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// VarmorClusterPolicyInformer provides access to a shared informer and lister for
// VarmorClusterPolicies.
type VarmorClusterPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.VarmorClusterPolicyLister
}

type varmorClusterPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewVarmorClusterPolicyInformer constructs a new informer for VarmorClusterPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewVarmorClusterPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredVarmorClusterPolicyInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredVarmorClusterPolicyInformer constructs a new informer for VarmorClusterPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredVarmorClusterPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1beta1().VarmorClusterPolicies().List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1beta1().VarmorClusterPolicies().Watch(context.TODO(), options)
			},
		},
		&varmorv1beta1.VarmorClusterPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *varmorClusterPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredVarmorClusterPolicyInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *varmorClusterPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&varmorv1beta1.VarmorClusterPolicy{}, f.defaultInformer)
}

func (f *varmorClusterPolicyInformer) Lister() v1beta1.VarmorClusterPolicyLister {
	return v1beta1.NewVarmorClusterPolicyLister(f.Informer().GetIndexer())
}
