{
 "title": "vArmor Status Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(profile_status_per_node, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Profile Processing Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Profile Processing Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(profile_processing_failure_total)",
     "legendFormat": "Failure Total"
    },
    {
     "expr": "sum(profile_processing_failure_total)",
     "legendFormat": "Success Total"
    }
   ]
  },
  {
   "title": "Profile Changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(profile_change_count_total) by (node_name)",
     "legendFormat": "{{node_name}} Total Changes"
    }
   ]
  },
  {
   "title": "Profile Failed Counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(profile_processing_failure_total) by (node_name)",
     "legendFormat": "{{node_name}} Failure Total"
    }
   ]
  },
  {
   "title": "Profile Success Counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(profile_processing_success_total) by (node_name)",
     "legendFormat": "{{node_name}} Success Total"
    }
   ]
  },
  {
   "title": "Profile Change Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(profile_change_count_total[5m])",
     "legendFormat": "Change Rate"
    }
   ]
  },
  {
   "title": "Profile Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(profile_processing_success_total[5m])",
     "legendFormat": "Success Rate"
    },
    {
     "expr": "rate(profile_processing_failure_total[5m])",
     "legendFormat": "Failure Rate"
    }
   ]
  },
  {
   "title": "Profile Status per Node",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    { "expr": "profile_status_per_node" }
   ]
  },
  { "title": "Webhook Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Webhook Requests Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "admission_requests_total", "legendFormat": "Total Requests" },
    { "expr": "mutated_requests_total", "legendFormat": "Mutated" },
    { "expr": "non_mutated_requests_total", "legendFormat": "Non-mutated" }
   ]
  },
  {
   "title": "Webhook Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "rate(admission_requests_total[5m])",
     "legendFormat": "Request Rate"
    },
    {
     "expr": "rate(mutated_requests_total[5m])",
     "legendFormat": "Mutation Rate"
    }
   ]
  },
  {
   "title": "Webhook Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(webhook_latency_sum) by (operation) / sum(webhook_latency_count) by (operation)\n",
     "legendFormat": "latency"
    }
   ]
  }
 ]
}