// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package bpfenforcer

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfLoopAuditEvent struct {
	_      structs.HostLayout
	Action uint32
	Type   uint32
	MntNs  uint32
	Tgid   uint32
	Ktime  uint64
	EventU struct {
		_      structs.HostLayout
		Buffer [4120]uint8
	}
}

type bpfLoopBuffer struct {
	_     structs.HostLayout
	Value [12288]uint8
}

type bpfLoopCapabilityRule struct {
	_       structs.HostLayout
	Mode    uint32
	Padding uint32
	Caps    uint64
}

type bpfLoopPodIp struct {
	_     structs.HostLayout
	Flags uint32
	Ipv4  [16]uint8
	Ipv6  [16]uint8
}

type bpfLoopPtraceRule struct {
	_           structs.HostLayout
	Mode        uint32
	Permissions uint32
	Flags       uint32
}

// loadBpfLoop returns the embedded CollectionSpec for bpfLoop.
func loadBpfLoop() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfLoopBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpfLoop: %w", err)
	}

	return spec, err
}

// loadBpfLoopObjects loads bpfLoop and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfLoopObjects
//	*bpfLoopPrograms
//	*bpfLoopMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfLoopObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpfLoop()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfLoopSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfLoopSpecs struct {
	bpfLoopProgramSpecs
	bpfLoopMapSpecs
	bpfLoopVariableSpecs
}

// bpfLoopProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfLoopProgramSpecs struct {
	VarmorBprmCheckSecurity *ebpf.ProgramSpec `ebpf:"varmor_bprm_check_security"`
	VarmorCapable           *ebpf.ProgramSpec `ebpf:"varmor_capable"`
	VarmorFileOpen          *ebpf.ProgramSpec `ebpf:"varmor_file_open"`
	VarmorMount             *ebpf.ProgramSpec `ebpf:"varmor_mount"`
	VarmorMoveMount         *ebpf.ProgramSpec `ebpf:"varmor_move_mount"`
	VarmorPathLink          *ebpf.ProgramSpec `ebpf:"varmor_path_link"`
	VarmorPathLinkTail      *ebpf.ProgramSpec `ebpf:"varmor_path_link_tail"`
	VarmorPathRename        *ebpf.ProgramSpec `ebpf:"varmor_path_rename"`
	VarmorPathRenameTail    *ebpf.ProgramSpec `ebpf:"varmor_path_rename_tail"`
	VarmorPathSymlink       *ebpf.ProgramSpec `ebpf:"varmor_path_symlink"`
	VarmorPtraceAccessCheck *ebpf.ProgramSpec `ebpf:"varmor_ptrace_access_check"`
	VarmorSocketConnect     *ebpf.ProgramSpec `ebpf:"varmor_socket_connect"`
	VarmorSocketCreate      *ebpf.ProgramSpec `ebpf:"varmor_socket_create"`
	VarmorUmount            *ebpf.ProgramSpec `ebpf:"varmor_umount"`
}

// bpfLoopMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfLoopMapSpecs struct {
	LinkProgs     *ebpf.MapSpec `ebpf:"link_progs"`
	RenameProgs   *ebpf.MapSpec `ebpf:"rename_progs"`
	V_auditRb     *ebpf.MapSpec `ebpf:"v_audit_rb"`
	V_bprmOuter   *ebpf.MapSpec `ebpf:"v_bprm_outer"`
	V_buffer      *ebpf.MapSpec `ebpf:"v_buffer"`
	V_capable     *ebpf.MapSpec `ebpf:"v_capable"`
	V_fileOuter   *ebpf.MapSpec `ebpf:"v_file_outer"`
	V_mountOuter  *ebpf.MapSpec `ebpf:"v_mount_outer"`
	V_netOuter    *ebpf.MapSpec `ebpf:"v_net_outer"`
	V_podIp       *ebpf.MapSpec `ebpf:"v_pod_ip"`
	V_profileMode *ebpf.MapSpec `ebpf:"v_profile_mode"`
	V_ptrace      *ebpf.MapSpec `ebpf:"v_ptrace"`
}

// bpfLoopVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfLoopVariableSpecs struct {
	InitMntNs *ebpf.VariableSpec `ebpf:"init_mnt_ns"`
	Unused    *ebpf.VariableSpec `ebpf:"unused"`
}

// bpfLoopObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfLoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfLoopObjects struct {
	bpfLoopPrograms
	bpfLoopMaps
	bpfLoopVariables
}

func (o *bpfLoopObjects) Close() error {
	return _BpfLoopClose(
		&o.bpfLoopPrograms,
		&o.bpfLoopMaps,
	)
}

// bpfLoopMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfLoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfLoopMaps struct {
	LinkProgs     *ebpf.Map `ebpf:"link_progs"`
	RenameProgs   *ebpf.Map `ebpf:"rename_progs"`
	V_auditRb     *ebpf.Map `ebpf:"v_audit_rb"`
	V_bprmOuter   *ebpf.Map `ebpf:"v_bprm_outer"`
	V_buffer      *ebpf.Map `ebpf:"v_buffer"`
	V_capable     *ebpf.Map `ebpf:"v_capable"`
	V_fileOuter   *ebpf.Map `ebpf:"v_file_outer"`
	V_mountOuter  *ebpf.Map `ebpf:"v_mount_outer"`
	V_netOuter    *ebpf.Map `ebpf:"v_net_outer"`
	V_podIp       *ebpf.Map `ebpf:"v_pod_ip"`
	V_profileMode *ebpf.Map `ebpf:"v_profile_mode"`
	V_ptrace      *ebpf.Map `ebpf:"v_ptrace"`
}

func (m *bpfLoopMaps) Close() error {
	return _BpfLoopClose(
		m.LinkProgs,
		m.RenameProgs,
		m.V_auditRb,
		m.V_bprmOuter,
		m.V_buffer,
		m.V_capable,
		m.V_fileOuter,
		m.V_mountOuter,
		m.V_netOuter,
		m.V_podIp,
		m.V_profileMode,
		m.V_ptrace,
	)
}

// bpfLoopVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfLoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfLoopVariables struct {
	InitMntNs *ebpf.Variable `ebpf:"init_mnt_ns"`
	Unused    *ebpf.Variable `ebpf:"unused"`
}

// bpfLoopPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfLoopObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfLoopPrograms struct {
	VarmorBprmCheckSecurity *ebpf.Program `ebpf:"varmor_bprm_check_security"`
	VarmorCapable           *ebpf.Program `ebpf:"varmor_capable"`
	VarmorFileOpen          *ebpf.Program `ebpf:"varmor_file_open"`
	VarmorMount             *ebpf.Program `ebpf:"varmor_mount"`
	VarmorMoveMount         *ebpf.Program `ebpf:"varmor_move_mount"`
	VarmorPathLink          *ebpf.Program `ebpf:"varmor_path_link"`
	VarmorPathLinkTail      *ebpf.Program `ebpf:"varmor_path_link_tail"`
	VarmorPathRename        *ebpf.Program `ebpf:"varmor_path_rename"`
	VarmorPathRenameTail    *ebpf.Program `ebpf:"varmor_path_rename_tail"`
	VarmorPathSymlink       *ebpf.Program `ebpf:"varmor_path_symlink"`
	VarmorPtraceAccessCheck *ebpf.Program `ebpf:"varmor_ptrace_access_check"`
	VarmorSocketConnect     *ebpf.Program `ebpf:"varmor_socket_connect"`
	VarmorSocketCreate      *ebpf.Program `ebpf:"varmor_socket_create"`
	VarmorUmount            *ebpf.Program `ebpf:"varmor_umount"`
}

func (p *bpfLoopPrograms) Close() error {
	return _BpfLoopClose(
		p.VarmorBprmCheckSecurity,
		p.VarmorCapable,
		p.VarmorFileOpen,
		p.VarmorMount,
		p.VarmorMoveMount,
		p.VarmorPathLink,
		p.VarmorPathLinkTail,
		p.VarmorPathRename,
		p.VarmorPathRenameTail,
		p.VarmorPathSymlink,
		p.VarmorPtraceAccessCheck,
		p.VarmorSocketConnect,
		p.VarmorSocketCreate,
		p.VarmorUmount,
	)
}

func _BpfLoopClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpfloop_bpfel.o
var _BpfLoopBytes []byte
