/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/bytedance/vArmor/apis/varmor/v1beta1"
	scheme "github.com/bytedance/vArmor/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ArmorProfilesGetter has a method to return a ArmorProfileInterface.
// A group's client should implement this interface.
type ArmorProfilesGetter interface {
	ArmorProfiles(namespace string) ArmorProfileInterface
}

// ArmorProfileInterface has methods to work with ArmorProfile resources.
type ArmorProfileInterface interface {
	Create(ctx context.Context, armorProfile *v1beta1.ArmorProfile, opts v1.CreateOptions) (*v1beta1.ArmorProfile, error)
	Update(ctx context.Context, armorProfile *v1beta1.ArmorProfile, opts v1.UpdateOptions) (*v1beta1.ArmorProfile, error)
	UpdateStatus(ctx context.Context, armorProfile *v1beta1.ArmorProfile, opts v1.UpdateOptions) (*v1beta1.ArmorProfile, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ArmorProfile, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ArmorProfileList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ArmorProfile, err error)
	ArmorProfileExpansion
}

// armorProfiles implements ArmorProfileInterface
type armorProfiles struct {
	client rest.Interface
	ns     string
}

// newArmorProfiles returns a ArmorProfiles
func newArmorProfiles(c *CrdV1beta1Client, namespace string) *armorProfiles {
	return &armorProfiles{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the armorProfile, and returns the corresponding armorProfile object, and an error if there is any.
func (c *armorProfiles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ArmorProfile, err error) {
	result = &v1beta1.ArmorProfile{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("armorprofiles").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ArmorProfiles that match those selectors.
func (c *armorProfiles) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ArmorProfileList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ArmorProfileList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("armorprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested armorProfiles.
func (c *armorProfiles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("armorprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a armorProfile and creates it.  Returns the server's representation of the armorProfile, and an error, if there is any.
func (c *armorProfiles) Create(ctx context.Context, armorProfile *v1beta1.ArmorProfile, opts v1.CreateOptions) (result *v1beta1.ArmorProfile, err error) {
	result = &v1beta1.ArmorProfile{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("armorprofiles").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(armorProfile).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a armorProfile and updates it. Returns the server's representation of the armorProfile, and an error, if there is any.
func (c *armorProfiles) Update(ctx context.Context, armorProfile *v1beta1.ArmorProfile, opts v1.UpdateOptions) (result *v1beta1.ArmorProfile, err error) {
	result = &v1beta1.ArmorProfile{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("armorprofiles").
		Name(armorProfile.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(armorProfile).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *armorProfiles) UpdateStatus(ctx context.Context, armorProfile *v1beta1.ArmorProfile, opts v1.UpdateOptions) (result *v1beta1.ArmorProfile, err error) {
	result = &v1beta1.ArmorProfile{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("armorprofiles").
		Name(armorProfile.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(armorProfile).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the armorProfile and deletes it. Returns an error if one occurs.
func (c *armorProfiles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("armorprofiles").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *armorProfiles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("armorprofiles").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched armorProfile.
func (c *armorProfiles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ArmorProfile, err error) {
	result = &v1beta1.ArmorProfile{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("armorprofiles").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
