/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/bytedance/vArmor/apis/varmor/v1beta1"
	scheme "github.com/bytedance/vArmor/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ArmorProfileModelsGetter has a method to return a ArmorProfileModelInterface.
// A group's client should implement this interface.
type ArmorProfileModelsGetter interface {
	ArmorProfileModels(namespace string) ArmorProfileModelInterface
}

// ArmorProfileModelInterface has methods to work with ArmorProfileModel resources.
type ArmorProfileModelInterface interface {
	Create(ctx context.Context, armorProfileModel *v1beta1.ArmorProfileModel, opts v1.CreateOptions) (*v1beta1.ArmorProfileModel, error)
	Update(ctx context.Context, armorProfileModel *v1beta1.ArmorProfileModel, opts v1.UpdateOptions) (*v1beta1.ArmorProfileModel, error)
	UpdateStatus(ctx context.Context, armorProfileModel *v1beta1.ArmorProfileModel, opts v1.UpdateOptions) (*v1beta1.ArmorProfileModel, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.ArmorProfileModel, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.ArmorProfileModelList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ArmorProfileModel, err error)
	ArmorProfileModelExpansion
}

// armorProfileModels implements ArmorProfileModelInterface
type armorProfileModels struct {
	client rest.Interface
	ns     string
}

// newArmorProfileModels returns a ArmorProfileModels
func newArmorProfileModels(c *CrdV1beta1Client, namespace string) *armorProfileModels {
	return &armorProfileModels{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the armorProfileModel, and returns the corresponding armorProfileModel object, and an error if there is any.
func (c *armorProfileModels) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ArmorProfileModel, err error) {
	result = &v1beta1.ArmorProfileModel{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("armorprofilemodels").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ArmorProfileModels that match those selectors.
func (c *armorProfileModels) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ArmorProfileModelList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.ArmorProfileModelList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("armorprofilemodels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested armorProfileModels.
func (c *armorProfileModels) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("armorprofilemodels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a armorProfileModel and creates it.  Returns the server's representation of the armorProfileModel, and an error, if there is any.
func (c *armorProfileModels) Create(ctx context.Context, armorProfileModel *v1beta1.ArmorProfileModel, opts v1.CreateOptions) (result *v1beta1.ArmorProfileModel, err error) {
	result = &v1beta1.ArmorProfileModel{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("armorprofilemodels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(armorProfileModel).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a armorProfileModel and updates it. Returns the server's representation of the armorProfileModel, and an error, if there is any.
func (c *armorProfileModels) Update(ctx context.Context, armorProfileModel *v1beta1.ArmorProfileModel, opts v1.UpdateOptions) (result *v1beta1.ArmorProfileModel, err error) {
	result = &v1beta1.ArmorProfileModel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("armorprofilemodels").
		Name(armorProfileModel.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(armorProfileModel).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *armorProfileModels) UpdateStatus(ctx context.Context, armorProfileModel *v1beta1.ArmorProfileModel, opts v1.UpdateOptions) (result *v1beta1.ArmorProfileModel, err error) {
	result = &v1beta1.ArmorProfileModel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("armorprofilemodels").
		Name(armorProfileModel.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(armorProfileModel).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the armorProfileModel and deletes it. Returns an error if one occurs.
func (c *armorProfileModels) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("armorprofilemodels").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *armorProfileModels) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("armorprofilemodels").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched armorProfileModel.
func (c *armorProfileModels) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ArmorProfileModel, err error) {
	result = &v1beta1.ArmorProfileModel{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("armorprofilemodels").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
