/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1beta1

// ArmorProfileListerExpansion allows custom methods to be added to
// ArmorProfileLister.
type ArmorProfileListerExpansion interface{}

// ArmorProfileNamespaceListerExpansion allows custom methods to be added to
// ArmorProfileNamespaceLister.
type ArmorProfileNamespaceListerExpansion interface{}

// ArmorProfileModelListerExpansion allows custom methods to be added to
// ArmorProfileModelLister.
type ArmorProfileModelListerExpansion interface{}

// ArmorProfileModelNamespaceListerExpansion allows custom methods to be added to
// ArmorProfileModelNamespaceLister.
type ArmorProfileModelNamespaceListerExpansion interface{}

// VarmorClusterPolicyListerExpansion allows custom methods to be added to
// VarmorClusterPolicyLister.
type VarmorClusterPolicyListerExpansion interface{}

// VarmorPolicyListerExpansion allows custom methods to be added to
// VarmorPolicyLister.
type VarmorPolicyListerExpansion interface{}

// VarmorPolicyNamespaceListerExpansion allows custom methods to be added to
// VarmorPolicyNamespaceLister.
type VarmorPolicyNamespaceListerExpansion interface{}
