/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1beta1 "github.com/bytedance/vArmor/apis/varmor/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeArmorProfileModels implements ArmorProfileModelInterface
type FakeArmorProfileModels struct {
	Fake *FakeCrdV1beta1
	ns   string
}

var armorprofilemodelsResource = schema.GroupVersionResource{Group: "crd.varmor.org", Version: "v1beta1", Resource: "armorprofilemodels"}

var armorprofilemodelsKind = schema.GroupVersionKind{Group: "crd.varmor.org", Version: "v1beta1", Kind: "ArmorProfileModel"}

// Get takes name of the armorProfileModel, and returns the corresponding armorProfileModel object, and an error if there is any.
func (c *FakeArmorProfileModels) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ArmorProfileModel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(armorprofilemodelsResource, c.ns, name), &v1beta1.ArmorProfileModel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ArmorProfileModel), err
}

// List takes label and field selectors, and returns the list of ArmorProfileModels that match those selectors.
func (c *FakeArmorProfileModels) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ArmorProfileModelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(armorprofilemodelsResource, armorprofilemodelsKind, c.ns, opts), &v1beta1.ArmorProfileModelList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.ArmorProfileModelList{ListMeta: obj.(*v1beta1.ArmorProfileModelList).ListMeta}
	for _, item := range obj.(*v1beta1.ArmorProfileModelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested armorProfileModels.
func (c *FakeArmorProfileModels) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(armorprofilemodelsResource, c.ns, opts))

}

// Create takes the representation of a armorProfileModel and creates it.  Returns the server's representation of the armorProfileModel, and an error, if there is any.
func (c *FakeArmorProfileModels) Create(ctx context.Context, armorProfileModel *v1beta1.ArmorProfileModel, opts v1.CreateOptions) (result *v1beta1.ArmorProfileModel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(armorprofilemodelsResource, c.ns, armorProfileModel), &v1beta1.ArmorProfileModel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ArmorProfileModel), err
}

// Update takes the representation of a armorProfileModel and updates it. Returns the server's representation of the armorProfileModel, and an error, if there is any.
func (c *FakeArmorProfileModels) Update(ctx context.Context, armorProfileModel *v1beta1.ArmorProfileModel, opts v1.UpdateOptions) (result *v1beta1.ArmorProfileModel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(armorprofilemodelsResource, c.ns, armorProfileModel), &v1beta1.ArmorProfileModel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ArmorProfileModel), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeArmorProfileModels) UpdateStatus(ctx context.Context, armorProfileModel *v1beta1.ArmorProfileModel, opts v1.UpdateOptions) (*v1beta1.ArmorProfileModel, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(armorprofilemodelsResource, "status", c.ns, armorProfileModel), &v1beta1.ArmorProfileModel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ArmorProfileModel), err
}

// Delete takes name of the armorProfileModel and deletes it. Returns an error if one occurs.
func (c *FakeArmorProfileModels) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(armorprofilemodelsResource, c.ns, name, opts), &v1beta1.ArmorProfileModel{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeArmorProfileModels) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(armorprofilemodelsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.ArmorProfileModelList{})
	return err
}

// Patch applies the patch and returns the patched armorProfileModel.
func (c *FakeArmorProfileModels) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ArmorProfileModel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(armorprofilemodelsResource, c.ns, name, pt, data, subresources...), &v1beta1.ArmorProfileModel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ArmorProfileModel), err
}
