name: ci-release-build
on:
  push:
    tags:
      - v*
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8

      - name: Set up llvm and apparmor
        run: ./.github/scripts/toolchain.sh

      - name: Run build
        run: make docker-build

      - name: Login to Docker Hub
        run: echo "${{ secrets.RELEASE_PASSWORD }}"||docker login -u=${{ secrets.PUSH_USERNAME }} elkeid-cn-beijing.cr.volces.com --password-stdin

      - name: Package helm chart
        run: make helm-package

      - name: Push image to registry
        run: make push
