name: ci-release-build
on:
  push:
    tags:
      - v*
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64/v8

      - name: Run build
        run: make docker-build

      - name: Package helm chart
        run: make helm-package

      - name: Login to Volc CR
        uses: docker/login-action@v3
        with:
          registry: elkeid-ap-southeast-1.cr.volces.com
          username: ${{ secrets.PUSH_USERNAME }}
          password: ${{ secrets.PUSH_PASSWORD }}

      - name: Push artifacts to registry
        run: make push
